### ISSUE TITLE
Syntax Error in gameState.py

### ISSUE THREAD

**Issue by BreePeterson** [brucepeterson/testbridge#2]
Probably a py2.7 syntax difference.

C:\Users\trfy9>python E:\Programming\Projects\testbridge\Bridge\gameState.py
  File "E:\Programming\Projects\testbridge\Bridge\gameState.py", line 212
    print "communicate with player", self.turn
                                  ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by brucepeterson** [comment]
Fixed
Developed in python2, running under python3.
